substitutions:
  firstname:
  - 투이
  - 우리
  - 마크
  - 존손
  - 루이
  - 왕밍
  - 지윤
  - 수희
  - 수연
  fullname:
  - 이지윤
  - 김수희
  - 최수연
  relation:
  - 동생
  - 친구
  country:
  - 베트남
  - 미국
  - 한국
  - 프랑스
  - 브라질
  - 케냐
  - 호주
  - 이탈리아
  - 영국
  - 러시아
  - 독일
  - 태국
  - 인도
  - 중국
  profession:
  - 가수
  - 의사
  - 선생님
  - 축구선수
  - 경찰
  - 영화배우
  - 운동선수
  - 요리사
  - 회사원
  - 학생
  - 대학생

# 1A questions for now
questions:
  ~firstname~ 씨, 어디에서 왔어요?: ~country~ 사람이에요
  이 사람은 누구예요?: ~firstname~ ~relation~이에요
  이름이 뭐예요?: 저는 ~fullname~이에요
  ~profession1~이에요?: 아니요. ~profession2~이에요
  무슨 일 하세요?: ~profession~이에요
